

 const tabsArr = [
  {id: 1,
    tab:'Lorem ipsum',
  content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent faucibus interdum lectus, vitae volutpat sapien dictum finibus. Меценат in risus odio. Donec aliquet, tortor id placerat scelerisque, turpis nunc porttitor enim, et fringilla augue ante euismod dui. Donec varius Erat Mauris, a ultrices nisi vestibulum quis, Quisque nec quam leo. Aliquam arcu purus, imperdiet vel mauris at, molestie rutrum magna. Phasellus venenatis pellentesque lorem vestibulum euismod. In hac Habitasse Platea dictumst. Curabitur dignissim at metus vel tempor. Меценат сит амет маурис ин nunc mollis convallis сит амет нон одио. Nulla vel dui lacinia augue iaculis molestie id vitae massa. Suspendisse nec justo feugiat, mollis ligula non, venenatis elit. Vestibulum sit amet lacus ex. Vestibulum elementum tristique sem, у rhoncus orci omare non. Etiam iaculis lorem nisi, non accumsan leo mattis fermentum'
  },
  { id: 2,
    tab:'Dolor sit',
    content: 'Integer sagittis risus eget augue varius pellentesque. Phasellus sodales nunc a orci lobortis aliquet. Etiam vel nisl ac ipsum lobortis mollis. Etiam mauris lorem, ullamcorper a ligula sit amet, tincidunt tristique enim. Proin eget quam sit amet leo tincidunt porttitor vel et turpis. Sed sollicitudin dapibus tortor, tempus aliquam quam lacinia eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tempor et neque posuere scelerisque. Morbi velit magna, ullamcorper vel metus a, t. Cura porta sagittis leo.'
  },
  {
    id:3,
    tab: 'Amet',
    content: 'Donec eu ante est. Nunc bibendum enim et pellentesque blandit. Mauris ut varius magna. Morbi vestibulum dolor vitae ex sodales scelerisque. Маурис in neque accumsan sapien tempor tincidunt. Donec accumsan sapien. Duis consectetur imperdiet purus, sed venenatis neque bibendum cursus. Vivamus porttitor ipsum ut sem congue congue. Integer dapibus nisi id scelerisque dictum. Nunc turpis nulla, pretium nec nulla ut, consectetur sagittis ex. Меценат in justo nec neque semper volutpat. Fusce semper risus sed laoreet dapibus. Duis tempus nisl posuere risus pretium gravida. Sed aliquet egestas justo, nec pulvinar odio interdum sit amet. Mauris ac molestie magna'
  } , 
  {id:4, 
  tab:'Consectetur',
  content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent faucibus interdum lectus, vitae volutpat sapien dictum finibus. Меценат in risus odio. Donec aliquet, tortor id placerat scelerisque, turpis nunc porttitor enim, et fringilla augue ante euismod dui. Donec varius Erat Mauris, a ultrices nisi vestibulum quis, Quisque nec quam leo. Aliquam arcu purus, imperdiet vel mauris at, molestie rutrum magna. Phasellus venenatis pellentesque lorem vestibulum euismod. In hac Habitasse Platea dictumst. Curabitur dignissim at metus vel tempor. Меценат сит амет маурис ин nunc mollis convallis сит амет нон одио. Nulla vel dui lacinia augue iaculis molestie id vitae massa. Suspendisse nec justo feugiat, mollis ligula non, venenatis elit. Vestibulum sit amet lacus ex. Vestibulum elementum tristique sem, у rhoncus orci omare non. Etiam iaculis lorem nisi, non accumsan leo mattis fermentum. Integer sagittis risus eget augue varius pellentesque. Phasellus sodales nunc a orci lobortis aliquet. Etiam vel nisl ac ipsum lobortis mollis. Etiam mauris lorem, ullamcorper a ligula sit amet, tincidunt tristique enim. Proin eget quam sit amet leo tincidunt porttitor vel et turpis. Sed sollicitudin dapibus tortor, tempus aliquam quam lacinia eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tempor et neque posuere scelerisque. Morbi velit magna, ullamcorper vel metus a, t. Cura porta sagittis leo. quis. Фаза сядьте Donec eu ante est. Nunc bibendum enim et pellentesque blandit. Mauris ut varius magna. Morbi vestibulum dolor vitae ex sodales scelerisque. Маурис in neque accumsan sapien tempor tincidunt. Donec accumsan sapien. Duis consectetur imperdiet purus, sed venenatis neque bibendum cursus. Vivamus porttitor ipsum ut sem congue congue. Integer dapibus nisi id scelerisque dictum. Nunc turpis nulla, pretium nec nulla ut, consectetur sagittis ex. Меценат in justo nec neque semper volutpat. Fusce semper risus sed laoreet dapibus. Duis tempus nisl posuere risus pretium gravida. Sed aliquet egestas justo, nec pulvinar odio interdum sit amet. Mauris ac molestie magna' 
  },
];

export default tabsArr;